#define LWMOVIE_D3D11_IDCT_NUMTHREADS	128
#define LWMOVIE_D3D11_BLOCK_FLAG_FORW_MOTION	(1 << 6)
#define LWMOVIE_D3D11_BLOCK_FLAG_BACK_MOTION	(1 << 7)
#define LWMOVIE_D3D11_BLOCK_FLAG_BOTH_MOTION	(LWMOVIE_D3D11_BLOCK_FLAG_FORW_MOTION|LWMOVIE_D3D11_BLOCK_FLAG_BACK_MOTION)
